#!/bin/bash

if [[ $1 == '' ]]
then
    echo "Please specify a command (e.g apps, containers)"
fi

if [[ $1 == 'help' ]]
then

echo "Available commands:"
echo "--> apps: List all the deployed apps"
echo "--> containers: List all the containers associated to each app"
fi

if [[ $1 == 'apps' ]]
then

echo "*************************************"
echo "*       Dookio apps deployed"
echo "*************************************"
curl -XGET $DOOKIO_SERVER_ADDRESS:8000/apps
printf "\nDone.\n"
fi

if [[ $1 == 'containers' ]]
then
   if [ "$#" != "3" ]; then 
       echo "You need to provide both the <user> and <app>. e.g dookio containers git apache"
   else
       echo "*************************************"
       echo "*       Dookio containers"
       echo "*************************************"
       echo "User: $2"
       echo "App: $3"
       curl -XGET "$DOOKIO_SERVER_ADDRESS:8000/containers?user=$2&repo=$3"
       printf "\nDone.\n"
   fi
fi
